version: '3.8'

services:
  simple-html:
    image: cr.yandex/crpg9ie34hq65l49usj2/devops-html
    build: .
    ports:
      - "3000:80"
    restart: unless-stopped
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./data:/usr/share/nginx/data