apiVersion: v1
kind: Service
metadata:
  name: nginx-app
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
    - name: http
      protocol: TCP
      port: 3000      # Внутренний порт сервиса
      targetPort: 80  # Порт контейнера Nginx
